import type { LatLngTuple } from "leaflet";
import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text, uniqueIndex, index } from "drizzle-orm/sqlite-core";

/**
 * Database schema (Drizzle ORM, SQLite).
 *
 * Conventions:
 * - Timestamps are ISO-8601 strings (UTC) stored as TEXT.
 * - Booleans are INTEGER 0/1 (Drizzle `mode: "boolean"`).
 * - Lists of coordinates are stored as JSON TEXT (`mode: "json"`).
 * - Ids are UUID strings generated by the application.
 */

const now = sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`;

// A place the trip stopped at. The core entity everything else hangs off.
export const stops = sqliteTable(
  "stops",
  {
    id: text("id").primaryKey(),
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    description: text("description"),
    latitude: real("latitude").notNull(),
    longitude: real("longitude").notNull(),
    link: text("link").notNull().default(""),
    statePark: integer("state_park", { mode: "boolean" }).notNull().default(false),
    nationalMonument: integer("national_monument", { mode: "boolean" }).notNull().default(false),
    nationalPark: integer("national_park", { mode: "boolean" }).notNull().default(false),
    // U.S. Army Corps of Engineers campground / recreation area.
    armyCorps: integer("army_corps", { mode: "boolean" }).notNull().default(false),
    // A one-night (or so) stop that isn't a destination: Harvest Host, Cracker Barrel, boondocking, rest area...
    overnightStop: integer("overnight_stop", { mode: "boolean" }).notNull().default(false),
    // Back at home base (Tallahassee) between legs of the trip.
    homeBase: integer("home_base", { mode: "boolean" }).notNull().default(false),
    // A city / town visit: the place itself was the point, not a park.
    cityStop: integer("city_stop", { mode: "boolean" }).notNull().default(false),
    // How we travelled for this stop: "fifth_wheel" | "minivan" | "motorhome" (see lib/vehicles.ts).
    vehicle: text("vehicle").notNull().default("fifth_wheel"),
    arrivalDate: text("arrival_date").notNull(),
    departureDate: text("departure_date").notNull(),
    // Waypoints of the journey *to* this stop: [[lat, lng], ...]
    journeyLatLongTuples: text("journey_lat_long_tuples", { mode: "json" })
      .$type<LatLngTuple[]>()
      .notNull()
      .default(sql`'[]'`),
    // Photo shown as this stop's cover. Nullable; cleared if the photo is deleted.
    coverPhotoId: text("cover_photo_id"),
    createdAt: text("created_at").notNull().default(now),
    updatedAt: text("updated_at").notNull().default(now),
  },
  (t) => [uniqueIndex("stops_slug_idx").on(t.slug), index("stops_arrival_idx").on(t.arrivalDate)]
);

// Blog entries. Imported Facebook posts and hand-written entries share this table.
export const posts = sqliteTable(
  "posts",
  {
    id: text("id").primaryKey(),
    stopId: text("stop_id").references(() => stops.id, { onDelete: "set null" }),
    title: text("title"),
    body: text("body").notNull(),
    postedAt: text("posted_at").notNull(),
    // "facebook" | "manual"
    source: text("source").notNull().default("manual"),
    // Stable id from the source system (e.g. Facebook post id) for idempotent re-imports.
    sourceId: text("source_id"),
    media: text("media", { mode: "json" }).$type<PostMedia[]>().notNull().default(sql`'[]'`),
    published: integer("published", { mode: "boolean" }).notNull().default(true),
    createdAt: text("created_at").notNull().default(now),
    updatedAt: text("updated_at").notNull().default(now),
  },
  (t) => [
    index("posts_stop_idx").on(t.stopId),
    index("posts_posted_at_idx").on(t.postedAt),
    uniqueIndex("posts_source_idx").on(t.source, t.sourceId),
  ]
);

// Every trip photo known to the system (scanned from the local Dropbox folder).
// Only curated ones get web variants.
export const photos = sqliteTable(
  "photos",
  {
    id: text("id").primaryKey(),
    // Path relative to PHOTO_LIBRARY_DIR, e.g. "/Pictures/2021/March 2021/2021-03-01 13.26.03.jpg".
    // Because the library is a synced Dropbox folder this is also the Dropbox cloud path.
    dropboxPath: text("dropbox_path").notNull(),
    dropboxRev: text("dropbox_rev"),
    fileName: text("file_name").notNull(),
    sizeBytes: integer("size_bytes"),
    // Capture time as written by the camera: naive local time, no zone ("2021-03-01T13:26:03").
    takenAt: text("taken_at"),
    latitude: real("latitude"),
    longitude: real("longitude"),
    width: integer("width"),
    height: integer("height"),
    stopId: text("stop_id").references(() => stops.id, { onDelete: "set null" }),
    // "unreviewed" | "suggested" | "kept" | "skipped"
    curationStatus: text("curation_status").notNull().default("unreviewed"),
    // Importer's suggestion score (higher = better candidate for the stop gallery).
    score: real("score"),
    sortOrder: integer("sort_order"),
    caption: text("caption"),
    // 64-bit perceptual hash (dHash) as 16 hex chars, for matching Facebook copies to originals.
    phash: text("phash"),
    // Paths (relative to the photo storage dir) of generated web variants, once downloaded.
    variants: text("variants", { mode: "json" }).$type<PhotoVariants | null>(),
    createdAt: text("created_at").notNull().default(now),
    updatedAt: text("updated_at").notNull().default(now),
  },
  (t) => [
    uniqueIndex("photos_dropbox_path_idx").on(t.dropboxPath),
    index("photos_stop_idx").on(t.stopId),
    index("photos_taken_at_idx").on(t.takenAt),
    index("photos_status_idx").on(t.curationStatus),
    index("photos_phash_idx").on(t.phash),
  ]
);

// ---- Import staging --------------------------------------------------------
// Nothing from an importer touches the live tables until it is approved here.

// A candidate stop proposed by clustering Dropbox photos by time + place.
export const stopCandidates = sqliteTable(
  "stop_candidates",
  {
    id: text("id").primaryKey(),
    suggestedName: text("suggested_name"),
    // Website of the nearby campground/park found in OSM/Wikidata, if any.
    suggestedLink: text("suggested_link"),
    latitude: real("latitude").notNull(),
    longitude: real("longitude").notNull(),
    arrivalDate: text("arrival_date").notNull(),
    departureDate: text("departure_date").notNull(),
    photoCount: integer("photo_count").notNull().default(0),
    // Ids of the photos that form this cluster.
    photoIds: text("photo_ids", { mode: "json" }).$type<string[]>().notNull().default(sql`'[]'`),
    // "pending" | "approved" | "rejected" | "merged"
    status: text("status").notNull().default("pending"),
    // Set when approved: the real stop created from this candidate.
    stopId: text("stop_id").references(() => stops.id, { onDelete: "set null" }),
    // Set when merged into another candidate.
    mergedIntoId: text("merged_into_id"),
    createdAt: text("created_at").notNull().default(now),
    updatedAt: text("updated_at").notNull().default(now),
  },
  (t) => [index("stop_candidates_status_idx").on(t.status)]
);

// A post parsed from the Facebook export, waiting for stop-linking review.
export const postCandidates = sqliteTable(
  "post_candidates",
  {
    id: text("id").primaryKey(),
    sourceId: text("source_id").notNull(),
    body: text("body").notNull(),
    postedAt: text("posted_at").notNull(),
    media: text("media", { mode: "json" }).$type<PostMedia[]>().notNull().default(sql`'[]'`),
    // Facebook check-in attached to the post, if any: { name, latitude?, longitude? }
    place: text("place", { mode: "json" }).$type<PostPlace | null>(),
    // Importer's best guess for the stop; null when ambiguous.
    suggestedStopId: text("suggested_stop_id").references(() => stops.id, { onDelete: "set null" }),
    // "pending" | "approved" | "rejected"
    status: text("status").notNull().default("pending"),
    postId: text("post_id").references(() => posts.id, { onDelete: "set null" }),
    createdAt: text("created_at").notNull().default(now),
    updatedAt: text("updated_at").notNull().default(now),
  },
  (t) => [
    uniqueIndex("post_candidates_source_idx").on(t.sourceId),
    index("post_candidates_status_idx").on(t.status),
  ]
);

// Ledger of every file seen by the photo scanner (in range or not), so rescans
// only run exiftool on new/changed files.
export const scannedFiles = sqliteTable("scanned_files", {
  path: text("path").primaryKey(),
  size: integer("size").notNull(),
  mtimeMs: integer("mtime_ms").notNull(),
  // 1 when the file produced a `photos` row (inside the trip date range).
  inRange: integer("in_range", { mode: "boolean" }).notNull().default(false),
  scannedAt: text("scanned_at").notNull().default(now),
});

// Reverse-geocoding results keyed by rounded "lat,lng" so we never hit Nominatim twice for one place.
export const geocodeCache = sqliteTable("geocode_cache", {
  key: text("key").primaryKey(),
  // Short display name, e.g. "Moab, UT"
  name: text("name").notNull(),
  raw: text("raw", { mode: "json" }),
  createdAt: text("created_at").notNull().default(now),
});

// ---- JSON column types -----------------------------------------------------

export interface PostMedia {
  kind: "photo" | "video";
  /** Path relative to the media storage directory. */
  path: string;
  /** Linked photos row when a Dropbox original was matched (see scripts/match-facebook-media.ts). */
  photoId?: string;
  /** Perceptual hash of this media file, cached so matching is cheap to re-run. */
  phash?: string;
  description?: string;
}

export interface PostPlace {
  name: string;
  latitude?: number;
  longitude?: number;
}

export interface PhotoVariants {
  thumb: string;
  medium: string;
  large: string;
}

export type StopRow = typeof stops.$inferSelect;
export type NewStopRow = typeof stops.$inferInsert;
export type PostRow = typeof posts.$inferSelect;
export type PhotoRow = typeof photos.$inferSelect;
export type StopCandidateRow = typeof stopCandidates.$inferSelect;
export type PostCandidateRow = typeof postCandidates.$inferSelect;
